;; Regenerates bench/expected.edn by running the real-Clojure reference
;; programs in bench/reference/. No vector space, no Python:
;;
;;   clojure -J-Xmx256m -M bench/reference/gen.clj
;;
;; Each reference file evaluates to a function of the bench task's parameters:
;; the (def sym value) forms of the bench file, read straight out of it, so
;; the sizes live in one place and the two programs cannot drift apart.

(require '[clojure.pprint :as pp] '[clojure.walk :as walk])

(def tasks
  [['fact "fact" "recursion depth, env chains; * is repeated addition"]
   ['fib "fib" "tree recursion, many short-lived env cells"]
   ['map-filter-reduce "map-filter-reduce" "list walking, closures as values (prelude map/filter/reduce)"]
   ['map-update-5 "map-update" "map rebuild on every assoc/update, n = 5 entries"]
   ['map-update-10 "map-update" "map rebuild on every assoc/update, n = 10 entries"]
   ['map-update-12 "map-update" "map rebuild on every assoc/update, n = 12 entries (largest exact at D=2048)"]
   ['graph-reach-8 "graph-reach" "maps of sets, set membership and enumeration, 8 nodes"]
   ['graph-reach-12 "graph-reach" "maps of sets, set membership and enumeration, 12 nodes"]
   ['graph-reach-20 "graph-reach" "maps of sets, set membership and enumeration, 20 nodes"]
   ['insertion-sort "insertion-sort" "long runs, many traces; Peano lt? is linear in the values"]
   ['metacircular "metacircular" "program as data, nested closures, VSA-map environments"]
   ['bst "bst" "deep nesting: BST as nested maps, insert/lookup/walk"]])

(defn params
  "The (def sym value) forms of a bench file, evaluated as data."
  [file]
  (into {}
        (for [form (read-string (str "[" (slurp file) "\n]"))
              :when (and (seq? form) (= 'def (first form)))]
          [(keyword (second form)) (eval (nth form 2))])))

(def expected
  (into {}
        (for [[task ref notes] tasks
              :let [file (str "bench/" task ".clj")
                    f (load-file (str "bench/reference/" ref ".clj"))]]
          [task {:file file :expected (f (params file)) :notes notes}])))

(defn- realise
  "Lazy seqs to lists, so the file reads back as plain data; number-keyed
  maps and number sets sorted, so it also reads well."
  [x]
  (walk/postwalk (fn [y]
                   (cond (seq? y) (apply list y)
                         (and (map? y) (every? number? (keys y))) (into (sorted-map) y)
                         (and (set? y) (every? number? y)) (into (sorted-set) y)
                         :else y))
                 x))

(spit "bench/expected.edn"
      (with-out-str
        (println ";; Generated by bench/reference/gen.clj from the real-Clojure reference")
        (println ";; programs; do not edit by hand.")
        (binding [*print-namespace-maps* false]
          (pp/pprint (into (sorted-map) (realise expected))))))

(doseq [[task {:keys [expected]}] (sort expected)]
  (println task (pr-str expected)))
